AWSTemplateFormatVersion: '2010-09-09'
Description: This runs Sagemaker for a Jupyter notebook to work with the Boreas dataset.
Resources:
 
    ExecutionRole: 
        Type: "AWS::IAM::Role"
        Properties: 
          AssumeRolePolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Principal: 
                  Service: 
                    - "sagemaker.amazonaws.com"
                Action: 
                  - "sts:AssumeRole"
          Path: "/"
          ManagedPolicyArns: 
            - "arn:aws:iam::aws:policy/AmazonS3FullAccess"

    NotebookLifecycleConfig:
        Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
        Properties:
          OnCreate:
          - Content:
              Fn::Base64: |
                #!/bin/sh

                set -e
                cat > /home/ec2-user/setup.sh << EOF
                #!/bin/bash
                sleep 10
                echo "Creating boreaspy3 conda environment"
                conda create --name boreaspy3 python="3.8.10" -y
                source activate boreaspy3
                conda install -c conda basemap proj4 nodejs ipywidgets -y 
                pip install botocore>=1.20.106 aiobotocore>=1.4.1 zarr>=2.9.5 rechunker>=0.4.2 ipykernel>=6.3.1 boto3>=1.17.106 dask>=2021.8.1 distributed>=2021.8.1 tornado>=6.1 cloudpickle>=1.6.0 msgpack>=1.0.2 blosc>=1.10.2 numpy>=1.21.2 pandas>=1.3.2 lz4>=3.1.3 netcdf4>=1.5.7 xarray>=0.19.0 bokeh>=2.2.3 s3fs>=2021.8.1 fsspec>=2021.8.1 h5netcdf>=0.11.0 h5py>=3.4.0 intake-esm>=2021.8.17 intake>=0.6.3 opencv-python>=4.5.3.56 matplotlib>=3.4.2 tqdm>=4.60.0 pyproj>=3.1.0 utm>=0.7.0 asrl-pysteam>=1.0.0
                python -m ipykernel install --user --name boreaspy3 --display-name "conda_boreaspy3"
                echo "Updating Jupyter config options"
                sed -i.bak 's/^#c.NotebookApp.iopub_data_rate_limit.*$/c.NotebookApp.iopub_data_rate_limit = 1.0e10/' ~/.jupyter/jupyter_notebook_config.py
                sed -i.bak 's/^#c.NotebookApp.iopub_msg_rate_limit.*$/c.NotebookApp.iopub_msg_rate_limit = 1.0e10/' ~/.jupyter/jupyter_notebook_config.py
                source /home/ec2-user/anaconda3/bin/deactivate
                source activate JupyterSystemEnv
                jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1
                source /home/ec2-user/anaconda3/bin/deactivate
                mkdir -p /home/ec2-user/boreas/boreas-2021-09-02-11-42
                aws s3 sync s3://boreas/boreas-2021-09-02-11-42 /home/ec2-user/SageMaker/boreas/boreas-2021-09-02-11-42 --exclude '*' --include 'applanix/*' --include 'calib/*' --include 'camera/163059759*' --include 'radar/163059759*' --include 'lidar/163059759*'
                source activate boreaspy3

                echo "Finished!"
                EOF
            
                chown ec2-user:ec2-user /home/ec2-user/setup.sh
                chmod +x /home/ec2-user/setup.sh

                sudo -u ec2-user -i nohup /home/ec2-user/setup.sh >/home/ec2-user/output.log 2>&1 &


    NotebookRepository:
        Type: AWS::SageMaker::CodeRepository
        Properties:
            GitConfig:
                RepositoryUrl: "https://github.com/utiasASRL/pyboreas"
                Branch: "master"

    NotebookInstance:
        Type: "AWS::SageMaker::NotebookInstance"
        Properties:
            NotebookInstanceName: !Join
            - ''
            - - INTRO-
              - !Select
                - 6
                - !Split
                  - '-'
                  - !Ref 'AWS::StackId'
            InstanceType: "ml.c5.xlarge"
            DefaultCodeRepository: !GetAtt NotebookRepository.CodeRepositoryName
            RoleArn: !GetAtt ExecutionRole.Arn
            LifecycleConfigName:  !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
            PlatformIdentifier: notebook-al2-v1
    
Outputs:
    JupyterNotebook:
        Value: !Join
        - ''
        - - https://
          - !Ref 'AWS::Region'
          - .console.aws.amazon.com/sagemaker/home?region=
          - !Ref 'AWS::Region'
          - '#/notebook-instances/openNotebook/'
          - !GetAtt 'NotebookInstance.NotebookInstanceName'
          - '?view=lab'
